# Generated by Django 5.0.6 on 2024-06-15 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('account_no', models.BigIntegerField(primary_key=True, serialize=False)),
                ('phno', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=100)),
                ('bal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('account_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.client')),
            ],
        ),
    ]
